### ISSUE TITLE
Add implicit checking for tag colours

### ISSUE THREAD

**Issue by VirtualVirtuoso** [NHSDigital/nhsuk-react-components-extensions#8]
At the moment, the Tag component is purely defined with SCSS. By moving it to a React component, we would be able to pass in the colour as a property, and leverage TypeScript to perform colour validation, preventing developers from using colours which haven't been defined.

An example could look like the following: 

```tsx
<Tag colour={Colour.Red}>Warning</Tag>
```

**Comment by Tomdango** [comment]
Closed as #10 has been merged
